### ISSUE TITLE
deepin-desktop-ts-convert should not mention nonexistent README.md file

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/deepin-gettext-tools#10]
https://github.com/linuxdeepin/deepin-gettext-tools/blob/master/src/desktop_ts_convert.pl#L55

This line should be edited or deleted.

**Comment by BLumia** [comment]
Should be resolved in https://github.com/linuxdeepin/deepin-gettext-tools/commit/1790ad9f9a119223959306ea7fc2e98b0b409b36 :)
