### ISSUE TITLE
change qmake to qmake-qt5

### ISSUE THREAD

**Issue by konstyab** [linuxdeepin/deepin-gettext-tools#2]
change qmake to qmake-qt5 in toplevel Makefile

Not sure about other distros. On my (ALTLinux, Sisyphus repository) having installed qt5 dev, I get "qmake-qt5" and there's no "qmake"

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
