### ISSUE TITLE
replace qmldevtools-private with qml in dupdate/src/linguist/lupdate/lupdate.pro

### ISSUE THREAD

**Issue by konstyab** [linuxdeepin/deepin-gettext-tools#3]
Trying to compile, I get:
make[4]: *** No rule to make target `/usr/lib64/libQt5QmlDevTools.a', needed by `../../../bin/lupdate'.  Stop.

For me, solution is change "QT += qmldevtools-private" to "QT += qml" in dupdate/src/linguist/lupdate/lupdate.pro

Not sure if this is correct

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
