### ISSUE TITLE
#include  <QDataStream> in dupdate/src/linguist/shared/qm.cpp

### ISSUE THREAD

**Issue by konstyab** [linuxdeepin/deepin-gettext-tools#4]
getiing errors like this:
/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/shared/qm.cpp: In member function 'bool Releaser::save(QIODevice*)':
/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/shared/qm.cpp:261:22: error: variable 'QDataStream s' has initializer but incomplete type
     QDataStream s(iod);

for me, worked adding this line to beginning of vi dupdate/src/linguist/shared/qm.cpp:
#include <QDataStream>

**Comment by konstyab** [comment]
#include <QDataStream>

**Comment by konstyab** [comment]
oops it doesnt's eccept lessthan sign

**Comment by konstyab** [comment]
QDataStream should be in #include

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
