### ISSUE TITLE
should be way for qt to add -I flags for QtQml/private

### ISSUE THREAD

**Issue by konstyab** [linuxdeepin/deepin-gettext-tools#5]
while building:

g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DPROEVALUATOR_CUMULATIVE -DPROEVALUATOR_INIT_PROPS -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate -I. -I/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/shared -I/usr/include/qt5/QtCore/5.6.2 -I/usr/include/qt5/QtCore/5.6.2/QtCore -I/usr/include/qt5 -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I.moc -I/usr/include/pcre -I/usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o .obj/qdeclarative.o /usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate/qdeclarative.cpp
/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate/qdeclarative.cpp:50:36: fatal error: private/qqmljsengine_p.h: No such file or directory
compilation terminated.

idk how to make qt put correct paths into INCLUDE (-I/usr/.... flags). I did manually this way:
sed -E -i.bak -e "s/^\\s*#include\\s+<private/#include <\/usr\/include\/qt5\/QtQml\/5.6.2\/QtQml\/private/g" dupdate/src/linguist/lupdate/qdeclarative.cpp

i think there should be way for qt to add -I flags automatically

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
