### ISSUE TITLE
change arguements of scanDirectives

### ISSUE THREAD

**Issue by konstyab** [linuxdeepin/deepin-gettext-tools#6]
while building:
g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DPROEVALUATOR_CUMULATIVE -DPROEVALUATOR_INIT_PROPS -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate -I. -I/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/shared -I/usr/include/qt5/QtCore/5.6.2 -I/usr/include/qt5/QtCore/5.6.2/QtCore -I/usr/include/qt5 -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I.moc -I/usr/include/pcre -I/usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o .obj/qdeclarative.o /usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate/qdeclarative.cpp
/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate/qdeclarative.cpp: In function 'bool load(Translator&, const QString&, ConversionData&, bool)':
/usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate/qdeclarative.cpp:471:43: error: no matching function for call to 'QQmlJS::Lexer::scanDirectives(HasDirectives*)'
         if (lex.scanDirectives(&directives)) {
                                           ^
In file included from /usr/src/RPM/BUILD/deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate/qdeclarative.cpp:52:0:
/usr/include/qt5/QtQml/5.6.2/QtQml/private/qqmljslexer_p.h:154:10: note: candidate: bool QQmlJS::Lexer::scanDirectives(QQmlJS::Directives*, QQmlJS::DiagnosticMessage*)
     bool scanDirectives(Directives *directives, DiagnosticMessage *error);

this patch makes it compilable, not sure about correctness:
diff -uraN deepin-gettext-tools-1.0.3-orig/dupdate/src/linguist/lupdate/qdeclarative.cpp deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate/qdeclarative.cpp
--- deepin-gettext-tools-1.0.3-orig/dupdate/src/linguist/lupdate/qdeclarative.cpp	2016-12-20 06:06:04.832452093 +0000
+++ deepin-gettext-tools-1.0.3/dupdate/src/linguist/lupdate/qdeclarative.cpp	2016-12-20 06:10:28.724152993 +0000
@@ -468,7 +468,8 @@
         Lexer lex(/*engine=*/ 0);
         HasDirectives directives(&lex);
         lex.setCode(code, 1, qmlMode);
-        if (lex.scanDirectives(&directives)) {
+	DiagnosticMessage notUsed;
+        if (lex.scanDirectives(&directives,&notUsed)) {
             if (directives()) {
                 // replace directives with white space characters
                 const int tokenOffset = directives.end();

**Comment by konstyab** [comment]
ok, failed to quote patch, but line should be this:
if (lex.scanDirectives(&directives,&notUsed)) {

and variable is defined this way:
DiagnosticMessage notUsed;

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
